### ISSUE TITLE
simplify JSON request/response by adding a "json: true" flag

### ISSUE THREAD

**Issue by Flet** [feross/simple-get#10]
Hey @feross 

Would you be in favor of a `json: true` option similar to `request`? 
>json - sets body to JSON representation of value and adds Content-type: application/json header. Additionally, parses the response body as JSON.

It feels like the majority of HTTP calls I'm making are JSON these days and it could be nice to avoid the `Content-Type`/`stringify`/`parse` dance.

I understand this makes thing less simple, so no worries if you want to keep it out! 👍

**Comment by feross** [comment]
@Flet I think this probably makes sense. Can you send a PR so I can see what that would look like?

**Comment by feross** [comment]
Fixed by @yciabaud in https://github.com/feross/simple-get/pull/13

**Comment by Flet** [comment]
Thanks @yciabaud!
