### ISSUE TITLE
Exclude uncessary files

### ISSUE THREAD

**Issue by tyrsius** [feross/simple-get#15]
This library aims to be the smallest wrapper around HTTP, but it includes its `text` directory in its installs. This directory is twice the size of the rest of the library.

Please exclude it with the `package.json` files, or an `.npmignore`.

**Comment by feross** [comment]
Thanks for the issue.

The `test` directory is just a 12kb file that's not required at runtime, or in browser builds. I think it's useful to publish it to npm since it's documentation about how the module works that's available when you're developing offline. I do that frequently.
