### ISSUE TITLE
rejectUnauthorized

### ISSUE THREAD

**Issue by stevenvachon** [feross/simple-get#19]
This doesn't look good in tests:
https://github.com/feross/simple-get/blob/master/test/basic.js#L11

**Comment by Flet** [comment]
I think its required in the tests since the test is running a server that uses self-signed certs to allow for quickly testing HTTPS without a lot of effort.

**Comment by feross** [comment]
What @Flet says is correct. This allows us to test https support without using a real SSL cert. Of course, this is only used in the test suite.

**Comment by stevenvachon** [comment]
That's what `rejectUnauthorized:false` does. People, such as myself, look to test suites for use case scenarios and finding global variable is not only not helpful, but discouraging.

**Comment by feross** [comment]
@stevenvachon PR welcome!
