### ISSUE TITLE
URL support

### ISSUE THREAD

**Issue by stevenvachon** [feross/simple-get#21]
[URL](https://developer.mozilla.org/en/docs/Web/API/URL), available in Node with [whatwg-url](https://npmjs.com/whatwg-url) (and `require("url").URL` in v7), is not currently supported.

**Comment by feross** [comment]
What would "supporting" URL entail?

**Comment by stevenvachon** [comment]
`auth` doesn't exist in `URL`. Instead it has `username` and `password` keys that will need to be concatenated with an infixed ":".

Also, swapping the use of `url.parse()` for `new URL()`.

**Comment by feross** [comment]
I don't see the point of replacing something that works in all version of node with something that works only in Node v7. Why exactly would we want to use `new URL()`?

**Comment by stevenvachon** [comment]
Because `url.parse()` is on track to being deprecated.

**Comment by feross** [comment]
I highly doubt that `url.parse()` will ever be deprecated, due to the massive effect on the ecosystem. But if that day does come, we can easily fix it *at that time*.

Isn't this just an implementation detail?

**Comment by stevenvachon** [comment]
Using browserify bundles in `url`. If it were using `URL`, we could rely on `window.URL`.

**Comment by feross** [comment]
Hm, that's actually a pretty nice benefit. Until it's more widespread though, this doesn't seem worth it, as we'd still need to include a polyfill for `URL`. We can revisit this in a year or so.
