### ISSUE TITLE
Document support of cookies, proxies, multipart and oauth

### ISSUE THREAD

**Issue by stevenvachon** [feross/simple-get#22]
Could pretty much just copy what [got](https://npmjs.com/got) does:
- https://github.com/sindresorhus/got#cookies
- https://github.com/sindresorhus/got#proxies
- https://github.com/sindresorhus/got#form-data
- https://github.com/sindresorhus/got#oauth

**Comment by feross** [comment]
This is a great idea. PR incoming!
