### ISSUE TITLE
ES5 Support

### ISSUE THREAD

**Issue by Miserlou** [feross/simple-get#25]
I need to use `simple-get` with ES5, which isn't do-able because of `Object.assign({}, opts)` (and maybe some others..).

**Comment by feross** [comment]
I sympathize, but `Object.assign` is pretty pervasive these days. It's only missing in unsupported versions of Node and IE11 (3.8% marketshare). 

Workaround to make it work for you: run it thru `browserify -t bubleify` and `require` that resulting file directly.

**Comment by Miserlou** [comment]
That's browser marketshare, and there are other places where Node is used, but sure.

For all those who end up here, I've published a polyfilled version to NPM: https://github.com/Miserlou/simple-get-es5

**Comment by feross** [comment]
@Miserlou Thanks for doing that.
