### ISSUE TITLE
Clear host header for cross-domain redirection

### ISSUE THREAD

**Issue by voidmonk** [feross/simple-get#32]
Found a minor issue: if a request redirects from hostname A to hostname B, then the `host` header from the previous request must be cleared, else it will return a HTTP error 404 (or similar) from the destination server of hostname B.

Example httpbin test URL: https://httpbin.org/redirect-to?url=http%3A%2F%2Fexample.com%2F (redirects from httpbin.org to example.com).

Possible fix: add `delete opts.headers['host']` to clear previous request's `host` header in `parseOptsUrl()` around [line 103](https://github.com/feross/simple-get/blob/master/index.js#L103).

As a sidenote, you probably don't need `delete opts.url` in `parseOptsUrl()` at [line 103](https://github.com/feross/simple-get/blob/master/index.js#L103). Should be safe to keep `opts.url`.

**Comment by feross** [comment]
For what it's worth, `request` opted to not fix this issue, i.e. to leave the `Host` header intact on redirects. But I think it's more sensible to remove it. https://github.com/requests/requests/issues/2366

Fixed in 2.7.1.
