### ISSUE TITLE
basic auth support

### ISSUE THREAD

**Issue by alessioalex** [feross/simple-get#57]
Hey @feross would you be open to a pull request to support basic auth? I know there's already OAuth but basic auth is still used here and there.

**Comment by Flet** [comment]
I wonder if this could be documented in the README like the oauth technique is (without adding code).

Maybe something like:
```
const user = 'someuser'
const pass= 'pa$$word'

get('http://example.com', {
  headers: {
    'user-agent': `my-module/${pkg.version} (https://github.com/username/my-module)`,
    authorization: 'Basic ' + Buffer.from(user + ':' + pass).toString('base64')
  }
})
```

**Comment by alessioalex** [comment]
Did not see that at the time I posted this. Considering that's the approach for OAuth, the http auth should be like the one in @Flet 's example (included in the `README`).

**Comment by feross** [comment]
Thanks for the code snippet, @Flet. Just added it to the readme!
