### ISSUE TITLE
Using simple-get in IONIC

### ISSUE THREAD

**Issue by luckypal** [feross/simple-get#58]
Hello.
I am gonna use this package in IONIC, but I can't. (Originally, I am using webtorrent in IONIC)
When I run project, it shows error like this.
![image](https://user-images.githubusercontent.com/35539437/75241575-f1fa3a00-578b-11ea-8607-7f99322eafe4.png)

I tried to find solution, and fix it to add this in package.json
![image](https://user-images.githubusercontent.com/35539437/75241640-1bb36100-578c-11ea-891f-f7ca1991d3e2.png)

It works well when I run this.
`ionic cordova emulate android -l`

But when I build release apk, it doesn't work, because http package can't be used in IONIC or Angular.
It shows "protocol.request is not function"

Is there any solution for this?

**Comment by feross** [comment]
You need to figure how to tell `iconic` to shim the Node.js `http` package for you.
