### ISSUE TITLE
Return Readable (response) stream?

### ISSUE THREAD

**Issue by tunnckoCore** [feross/simple-get#6]
Same as `request` and `got.stream` to allow things like `.pipe(fs.createWriteStream(fp))?

 Maybe separate method, would be the way.

**Comment by feross** [comment]
This is already supported. It's the first example in the readme:

```js
var get = require('simple-get')

get('http://example.com', function (err, res) {
  if (err) throw err
  console.log(res.statusCode) // 200
  res.pipe(process.stdout) // `res` is a stream
})
```

**Comment by tunnckoCore** [comment]
Oh., Yea I see that. Problem is that it is possible in callback. It not returned directly from execution of simple-get - exactly what i need.

**Comment by feross** [comment]
That's because the request object is returned from `get`. This package is trying to be as close to node's http as possible, and that returns the request object.

If we returned the response instead, how would you get access to the request object?

**Comment by feross** [comment]
You can wrap this package and accomplish what you want pretty easily using `through2`.
